# Settings.yml
---
conf.py:
  ##==========================================
  ## define configuration data for conf.py as
  ## "parameter: value" pairs here:
  ##------------------------------------------
  todo_include_todos: True
  copyright: 2013 to now
  project: Documentation Contribution Guide
  version: 0.2
  release: 0.2.0
...
